### ISSUE TITLE
Add "Copy to Clipboard" link to code blocks

### ISSUE THREAD

**Issue by skrysmanski** [skrysmanski/blogtext#10]
It would be nice to have (optionally) a "Copy to Clipboard" button attached to code blocks.

**Comment by spiralofhope** [comment]
BlogText uses GeSHi for syntax highlighting. I'm not certain, but this request might be better suited upstream to them.

http://qbnz.com/highlighter/

**Comment by skrysm** [comment]
I've stopped developing BlogText - see README for more details.
