### ISSUE TITLE
Highlighting of code line without line numbering or prog language

### ISSUE THREAD

**Issue by skrysmanski** [skrysmanski/blogtext#12]
Currently highlighting a line in a code block only works if the attribute `lang` and/or `line` is specified. This should also work without these two attributes.

**Comment by spiralofhope** [comment]
Is this a problem upstream with GeSHi?

I actually went looking to see if there was some sort of "plain text" non-highlighting language, but they don't have such a thing.

**Comment by skrysm** [comment]
I've stopped developing BlogText - see README for more details.
