### ISSUE TITLE
Implement whitelist for plain text URL parsing

### ISSUE THREAD

**Issue by skrysmanski** [skrysmanski/blogtext#13]
(from Berend Dekens)

I love your plugin! After years of refactoring HTML every time I tried upgrading my websites I love that I can just type simple markups and let them be converted into proper HTML later on.

I’d like to report a bug though (I found the bug tracker but it requires me to register): the regex to capture plain URLs from the text accepts every protocol as it searches for a string. I have some plugins like the Youtube Lyte embedder which use a special URL to extract a link to a video and replace it with object code.

Perhaps this can be added to your plugin? An option to convert all links (like it does by default) or a list of protocols. I’ve inserted something like: (http|https|ftp|sftp|ssh|ts3) for my site.

**Comment by skrysm** [comment]
I've stopped developing BlogText - see README for more details.
