### ISSUE TITLE
BlogText cache is incompatible with Crayon Syntax Highlighter

### ISSUE THREAD

**Issue by skrysmanski** [skrysmanski/blogtext#20]
(from 夏睿（Harry Summer))

Crayon Syntax Highlighter precaculate a codeblock ID in the_post filter, which is before BlogText's processing. And replace the ID with real content after BlogText's processing. That ID may vary from time to time, but BlogText would give a constant one from the cache. This would make the code of Crayon Syntax Hightlighter cannot display.

I'm wondering if you can add an option for us to switch off the cache function of BlogText, so that if would be compatible with these sort of pre-processing.

**Comment by skrysm** [comment]
I've stopped developing BlogText - see README for more details.
