### ISSUE TITLE
Footnotes functionality

### ISSUE THREAD

**Issue by spiralofhope** [skrysmanski/blogtext#38]
- https://wordpress.org/support/plugin/footnotes/
- https://cheret.de/plugins/footnotes-2/
- https://blog.spiralofhope.com/?p=35982

As the author is not a programmer, I wonder if you're interested in either picking up this project or implementing a simple footnotes/endnotes feature.

**Comment by skrysm** [comment]
I've stopped developing BlogText - see README for more details.
