### ISSUE TITLE
Previewing/saving content with yola dot com produces a "403 Forbidden" error

### ISSUE THREAD

**Issue by spiralofhope** [skrysmanski/blogtext#39]
- PHP 7.4.22
- WordPress 5.8
- BlogText 0.9.9

### Steps to reproduce

- Begin a new post
- Type `yola.com`
- Click "preview" on the right-hand side

A new tab opens, with the message:
```

403
Forbidden

Access to this resource on the server is denied!
```

### Notes

- This precise message is likely produced by my hosting and could be different for others.
- I don't know if this is related to #33
- I don't know if this is related to #37
- All other addons have been disabled (I wondered if this was some sort of anti-spam measure)

**Comment by skrysmanski** [comment]
@spiralofhope I can't reproduce this. For me it just prints `yola.com`. I'm guessing this is caused by another WordPress plugin. Can you verify this behavior when you have only BlogText enabled?

**Comment by spiralofhope** [comment]
I disabled other plugins when I originally reproduced this.

I re-tested right now, and I also cannot reproduce it!

BlogText 0.9.10
WordPress 5.8.1
PHP 7.4.23

Maybe WordPress or PHP had some temporary hate for that website?  Very strange!
